# Generated by Django 5.2.6 on 2025-09-26 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0006_alter_pedido_estado_alter_pedido_subtotal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='platos',
        ),
    ]
