# Generated by Django 5.2.6 on 2025-09-26 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0007_remove_pedido_platos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='menu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.menu'),
        ),
    ]
