# Generated by Django 5.2.5 on 2025-08-26 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.proveedor'),
        ),
        migrations.AddField(
            model_name='compra',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.unidad'),
        ),
        migrations.AddField(
            model_name='plato',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.producto'),
        ),
        migrations.AddField(
            model_name='plato',
            name='productos',
            field=models.ManyToManyField(related_name='platos', through='aplicacion.PlatoProducto', to='aplicacion.producto'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('entregado', 'Entregado')], max_length=20),
        ),
    ]
