# Generated by Django 5.2.6 on 2025-09-09 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_remove_venta_admin_venta_administrador_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='administrador',
            new_name='admin',
        ),
    ]
