# Generated by Django 5.2.6 on 2025-09-09 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_rename_administrador_venta_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('online', 'Online')], default='efectivo', max_length=50),
        ),
    ]
