# Generated by Django 5.2.5 on 2025-08-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plato',
            name='productos',
            field=models.ManyToManyField(related_name='platos', through='aplicacion.PlatoProducto', to='aplicacion.producto'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('entregado', 'Entregado')], max_length=20),
        ),
    ]
