# Generated by Django 5.2.4 on 2025-08-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
