# Generated by Django 5.2.4 on 2025-07-29 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_salidainventario'),
        ('aplicacion', '0002_usuario_cargo'),
    ]

    operations = [
    ]
