# Generated by Django 5.2.4 on 2025-08-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_merge_0002_salidainventario_0002_usuario_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='numero',
            field=models.CharField(default='M01', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
